tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "on-error-container": "#93000a",
                "on-tertiary-fixed": "#002108",
                "surface-bright": "#f7f9ff",
                "surface-variant": "#dae3ef",
                "on-tertiary-container": "#c0ffc1",
                "surface-tint": "#005bc0",
                "primary": "#0051ae",
                "surface-container-highest": "#dae3ef",
                "on-surface": "#141c25",
                "inverse-primary": "#adc6ff",
                "on-error": "#ffffff",
                "primary-fixed-dim": "#adc6ff",
                "background": "#f7f9ff",
                "surface-container-high": "#e0e9f5",
                "tertiary-container": "#177d35",
                "surface-container-lowest": "#ffffff",
                "tertiary": "#006225",
                "inverse-surface": "#29313a",
                "tertiary-fixed-dim": "#7cdb87",
                "secondary-fixed-dim": "#c3c6cd",
                "surface": "#f7f9ff",
                "error": "#ba1a1a",
                "primary-container": "#0969da",
                "tertiary-fixed": "#97f8a1",
                "outline-variant": "#c2c6d6",
                "secondary-container": "#dde0e6",
                "on-background": "#141c25",
                "surface-container": "#e6effa",
                "on-secondary-container": "#5f6369",
                "on-primary": "#ffffff",
                "primary-fixed": "#d8e2ff",
                "surface-container-low": "#ecf4ff",
                "error-container": "#ffdad6",
                "on-primary-fixed": "#001a41",
                "on-tertiary-fixed-variant": "#00531e",
                "on-surface-variant": "#424753",
                "on-secondary-fixed": "#181c21",
                "secondary": "#5b5f64",
                "surface-dim": "#d2dbe6",
                "inverse-on-surface": "#e9f2fd",
                "on-tertiary": "#ffffff",
                "on-primary-fixed-variant": "#004493",
                "secondary-fixed": "#e0e2e9",
                "on-secondary-fixed-variant": "#43474d",
                "on-primary-container": "#ecefff",
                "outline": "#727785",
                "on-secondary": "#ffffff"
            },
            "borderRadius": {
                "DEFAULT": "0.125rem",
                "lg": "0.25rem",
                "xl": "0.5rem",
                "full": "0.75rem"
            },
            "spacing": {
                "margin-mobile": "16px",
                "container-max": "1280px",
                "base": "8px",
                "gutter": "24px",
                "margin-desktop": "32px"
            },
            "fontFamily": {
                "headline-md": ["Geist"],
                "body-lg": ["Geist"],
                "headline-lg": ["Geist"],
                "label-sm": ["JetBrains Mono"],
                "body-md": ["Geist"],
                "headline-xl": ["Geist"],
                "headline-lg-mobile": ["Geist"],
                "label-md": ["JetBrains Mono"]
            },
            "fontSize": {
                "headline-md": ["24px", {"lineHeight": "1.4", "fontWeight": "600"}],
                "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
                "headline-lg": ["32px", {"lineHeight": "1.25", "letterSpacing": "-0.01em", "fontWeight": "600"}],
                "label-sm": ["12px", {"lineHeight": "1.4", "fontWeight": "400"}],
                "body-md": ["16px", {"lineHeight": "1.5", "fontWeight": "400"}],
                "headline-xl": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700"}],
                "headline-lg-mobile": ["24px", {"lineHeight": "1.3", "fontWeight": "600"}],
                "label-md": ["14px", {"lineHeight": "1.4", "fontWeight": "500"}]
            }
        },
    },
}
